# Generated by Django 2.2.4 on 2023-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_auto_20230521_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
