# Generated by Django 2.2.4 on 2023-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_auto_20230521_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(max_length=100, verbose_name='类型'),
        ),
    ]
