# Generated by Django 2.2.4 on 2023-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_auto_20230522_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.FloatField(max_length=10, verbose_name='金额'),
        ),
    ]
